basePath: /
consumes:
- application/json
info:
  description: Documentation for matrix API
  title: E-Core Test
  version: 1.0.0
paths:
  /echo:
    get:
      consumes:
      - multipart/form-data
      description: Returns a representation of the file as a string
      operationId: echo
      responses:
        "200":
          $ref: '#/responses/matrixResponse'
produces:
- text/plain
responses:
  matrixResponse:
    description: Representation of request response
    headers:
      Body:
        description: 'in: Body'
        type: string
schemes:
- http
swagger: "2.0"
