version: '3'
services:
  tests:
    build:
      context: ../..
      dockerfile: docker/e2e/Dockerfile
    depends_on:
      - test_server
    environment:
      PORT: ":8080"
      TEST_SERVER_HOST: test_server
  test_server:
    build:
      context: ../..
      dockerfile: docker/e2e/server/Dockerfile
    ports:
      - 8080:8080
    environment:
      HOST_PORT: 8080
